language: node_js
node_js:
  - 0.12
  
env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - master
  - /^release-.*/

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install ts-mocha -g --no-save
  - npm install

git:
  depth: 1